import './globals.css'

import type { Metadata } from 'next'
import React from 'react'

import MenuComponent from '@/src/components/MenuComponent'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <MenuComponent />
        {children}
      </body>
    </html>
  )
}
